version: 2.1
jobs:
   configure_infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["7c:0d:8b:44:98:85:f4:91:34:70:f2:5a:9d:40:29:8c"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory playbook.yml

workflows:
  my_workflow:
    jobs:
      - configure_infra


